### ISSUE TITLE
Stack 22 breaks azure cognitive services package

### ISSUE THREAD

**Issue by tadeoos** [heroku/stack-images#226]
Hey there!
Thanks a lot for your work on all of these images!
I wanted to report in case this flew under your radar. I recently upgraded my Heroku stack to 22, but unfortunately needed to revert to 20, as it broke my azure integration.

Version Info:
- Heroku stack 22
- Python 3.10.6
- azure_cognitiveservices_speech==1.23.0 (pip requirement)

upon running:
```python
self.synthesizer = speechsdk.SpeechSynthesizer(speech_config=self.speech_config, audio_config=None)
```
I received an error:
```
RuntimeError:
Runtime error: Failed to initialize platform (azure-c-shared). Error: 2153
[CALL STACK BEGIN]

/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1b75e1) [0x7f33a29b75e1]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1dbcfb) [0x7f33a29dbcfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x99f68) [0x7f33c7a6df68]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1dceb2) [0x7f33a29dceb2]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1a0a49) [0x7f33a29a0a49]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1a3197) [0x7f33a29a3197]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1bedaa) [0x7f33a29bedaa]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d667c) [0x7f33a29d667c]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x189f82) [0x7f33a2989f82]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0xdf613) [0x7f33a28df613]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1bedaa) [0x7f33a29bedaa]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x181eb1) [0x7f33a2981eb1]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1e9d31) [0x7f33a29e9d31]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(synthesizer_create_speech_synthesizer_from_config+0xf3) [0x7f33a28c4be0]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/_speech_py_impl.so(+0xd38cc) [0x7f33a30d38cc]
/app/.heroku/python/lib/python3.10/site-packages/azure/cognitiveservices/speech/_speech_py_impl.so(+0x6bdb3) [0x7f33a306bdb3]
/app/.heroku/python/lib/libpython3.10.so.1.0(+0x156238) [0x7f33c7d57238]
[CALL STACK END]
```

Not sure if this is your problem to fix or Azure's but wanted to make sure you guys are aware of this.

**Comment by edmorley** [comment]
Hi!

This seems to be unrelated to the stack images - it occurs on the official Ubuntu 22.04 images too:

```
$ docker run --rm -it --platform linux/x86_64 ubuntu:22.04 bash
root@777a1cf92cfa:/# apt-get update -qq && apt-get install -qqy python3 python3-pip
root@777a1cf92cfa:/# pip install azure_cognitiveservices_speech==1.23.0
root@777a1cf92cfa:/# python3
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import azure.cognitiveservices.speech as speechsdk
>>> speech_config = speechsdk.SpeechConfig(subscription="FOO", region="BAR")
>>> speechsdk.SpeechSynthesizer(speech_config=speech_config)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/speech.py", line 1598, in __init__
    self._impl = self._get_impl(impl.SpeechSynthesizer, speech_config, audio_config,
  File "/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/speech.py", line 1703, in _get_impl
    _impl = synth_type._from_config(speech_config._impl, None if audio_config is None else audio_config._impl)
RuntimeError: Runtime error: Failed to initialize platform (azure-c-shared). Error: 2153
[CALL STACK BEGIN]

/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1b75e1) [0x40031b75e1]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1dbcfb) [0x40031dbcfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x99f68) [0x4001ffaf68]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1dceb2) [0x40031dceb2]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1a0a49) [0x40031a0a49]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1a3197) [0x40031a3197]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1bedaa) [0x40031bedaa]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d667c) [0x40031d667c]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x189f82) [0x4003189f82]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0xdf613) [0x40030df613]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1bedaa) [0x40031bedaa]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x181eb1) [0x4003181eb1]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1e9d31) [0x40031e9d31]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(synthesizer_create_speech_synthesizer_from_config+0xf3) [0x40030c4be0]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/_speech_py_impl.so(+0xd38cc) [0x4002ad38cc]
/usr/local/lib/python3.10/dist-packages/azure/cognitiveservices/speech/_speech_py_impl.so(+0x6bdb3) [0x4002a6bdb3]
python3(+0x15b798) [0x400015b798]
[CALL STACK END]
```

I would report this to the package maintainers.

**Comment by tadeoos** [comment]
Thanks for checking! I'm gonna take it up with them :)
